# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# HTTP settings for reverse proxy
http:
  use_x_forwarded_for: true
  trusted_proxies: 
    - 127.0.0.1

# General home assistant settings
homeassistant:
  packages: !include_dir_named packages

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml